 - name: adding SSH access to a security group
   amazon.aws.ec2_group:
      name: mujab-security
      description: security group for ansible
      region: us-east-1
      rules:
        - proto: tcp
          from_port: 3001
          to_port: 3001
          cidr_ip: 0.0.0.0/0

        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0

        - proto: tcp
          from_port: 3000
          to_port: 3000
          cidr_ip: 0.0.0.0/0

        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

   register: security_group 

 - name: Launch EC2 instance
   amazon.aws.ec2_instance:
      image_id: {{ ec2_image_id }}
      instance_type: {{ ec2_instance_type }}
      key_name: {{ ec2_key_name }}
      security_group: {{ security_group_name }}
      region: {{ aws_region }}
      state: running
      wait: true
   register: ec2_instance

 - name: Display EC2 instance info
   debug:
      msg: "Instance created successfully: {{ ec2_instance }}"
  
 

  