---
- name: Provision and Configure EC2 Server
  hosts: localhost
  gather_facts: false
 

  tasks:
    - name: adding SSH access to a security group
      amazon.aws.ec2_group:
        name: default
        description: security group for ansible
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 3001
            to_port: 3001
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 3000
            to_port: 3000
            cidr_ip: 0.0.0.0/0

          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

      register: security_group


    - name: Launch EC2 instance
      amazon.aws.ec2_instances:
        image_id: ami-0b6d9d3d33ba97d99
        instance_type: t3.micro
        key_name: mujab-temp 
        security_group: default
        region: us-east-1
        state: running
        wait: true
      register: ec2_instance

    - name: Display EC2 instance info
      debug:
        msg: "Instance ID: {{ ec2_instance.instances[0].instance_id }}"


