---
- name: Provision and Configure EC2 Server
  hosts: localhost
  gather_facts: false
  roles:
    - ec2_launch


- name: Configure the launched EC2 instance
  hosts: launched_ec2_instances
  gather_facts: true
  roles:
    - common
    
    

 